import{a as d,S as v,i as c}from"./assets/vendor-D0cagnvz.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))u(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&u(l)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function u(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();d.defaults.baseURL="https://pixabay.com/api/";d.defaults.params={key:"48120556-fdb679f2a2804b1816b5c1c88"};async function m(o){try{const e=await d.get("",{params:{q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:p}});return{images:e.data.hits,totalHits:e.data.totalHits}}catch(e){throw console.error("Error fetching images:",e.message),e}}const L=document.querySelector(".gallery");function h(o){const e=o.map(r=>`
        <li class = item>
        <div class = conteiner-img>
          <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" />
        </div>
      </a>
      <div class = image-info>
          <p class = info-title>Likes <span class = info-value>${r.likes}</span></p>
          <p class = info-title>Views <span class = info-value>${r.views}</span></p>
          <p class = info-title>Comments <span class = info-value>${r.comments}</span></p>
          <p class = info-title>Downloads <span class = info-value>${r.downloads}</span></p>
      </div>
        </li>
      `).join("");L.insertAdjacentHTML("beforeend",e)}const q=document.querySelector(".search-form"),S=document.querySelector(".search-input"),f=document.querySelector(".gallery"),y=document.querySelector(".loader-wrapper"),n=document.querySelector(".load-more-btn");let p=1,a="",i=0;function g(){y.style.display="flex"}function w(){y.style.display="none"}let b=new v(".gallery a",{captionsData:"alt",captionDelay:250});q.addEventListener("submit",async o=>{if(o.preventDefault(),a=S.value.trim(),a===""){c.show({messageColor:"#fff",color:"#EF4040",position:"topRight",message:"Please enter a search term!"});return}f.innerHTML="",p=1,i=0,n.style.display="none",g();try{const{images:e,totalHits:r}=await m(a);if(e.length===0){c.show({messageColor:"#fff",color:"#EF4040",position:"topRight",maxWidth:432,message:"Sorry, there are no images matching your search query. Please try again!"});return}h(e),b.refresh(),i+=e.length,e.length<r&&(n.style.display="block")}catch(e){console.log(e)}finally{w()}});n.addEventListener("click",async()=>{p+=1,g();try{const{images:o,totalHits:e}=await m(a);h(o),b.refresh(),i+=o.length,x(),(o.length<15||i>=e)&&(n.style.display="none",c.show({messageColor:"#fff",color:"#FFA500",position:"topRight",maxWidth:432,message:"We're sorry, but you've reached the end of search results."}))}catch(o){console.log(o)}finally{w()}});function x(){if(f.firstElementChild){const{height:o}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
